userAuthentication/authenticationApp/urls.py
from django.urls import path
from authenticationApp import views

app_name = 'authenticationApp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

userAuthentication/userAuthentication/urls.py
from django.contrib import admin
from django.urls import path, include
from authenticationApp import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('authenticationApp/', include('authenticationApp.urls')),
    path('logout/', views.user_logout, name="logout"),
    path('special/',views.special,name="special")
]

userAuthentication/authenticationApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    #Sort of like inheriting from User but not really, it's kind of like extending the class
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #addtional
    #They don't have to fill it out
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank = True)

    def __str__(self):
        return self.user.username

userAuthentication/authenticationApp/forms.py
from django import forms
from django.contrib.auth.models import User
from authenticationApp.models import UserProfileInfo
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

userAuthentication/authenticationApp/views.py
from django.shortcuts import render
from authenticationApp.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request, 'authenticationApp/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, NICE!!")

#decorator for views that only logged in people can access
@login_required
def user_logout(request):
    #built in django logout
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            #Defining the one to one relationship
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'authenticationApp/registration.html', {'user_form':user_form, 'profile_form': profile_form, 'registered': registered})



def user_login(request):
    if request.method == "POST":
        #For simple html form
        username = request.POST.get('username')
        password = request.POST.get('password')
        #automatically authenticating user
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                #Logging in the user, thank you Django
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'authenticationApp/login.html',{})

userAuthentication/templates/authenticationApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
      <div class="container">
        <ul class="navbar-nav">
          <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
          <a class="nav-item navbar-link" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item navbar-link" href="{% url 'authenticationApp:register'%}">Register</a>
          <!-- if user passed the authentication function in views.py -->
          {% if user.is_authenticated %}
            <a class="nav-item navbar-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
            <a class="nav-item navbar-link" href="{% url 'authenticationApp:user_login' %}">Login</a>
          {% endif %}
          <a class="nav-item navbar-link" href="{% url 'special' %}">Special Page!</a>
        </ul>

      </div>

    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock%}
    </div>

  </body>
</html>

userAuthentication/templates/authenticationApp/index.html
{% extends "authenticationApp/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Django Level Five</h1>

</div>

{% endblock %}

userAuthentication/templates/authenticationApp/login.html
{% extends 'authenticationApp/base.html'%}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'authenticationApp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">
  </form>
</div>
{% endblock %}

userAuthentication/templates/authenticationApp/registration.html
{% extends 'authenticationApp/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}
</div>

{% endblock %}